import * as THREE from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
const palette={U01:'#36B9FF',U02:'#FF9B35',U03:'#B68AFF',U04:'#35DAB1',U05:'#FF638A',U06:'#F2D447',U07:'#5574F5',U08:'#C7E987',U09:'#EBAFE5'};
let segment=0,playing=false,elapsed=0,applyState=()=>{},ready=false,synced=false;
addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='anlb-scene')return;const next=Math.max(0,Math.min(2,Number(e.data.segment)||0)),changed=next!==segment;segment=next;playing=!!e.data.playing;elapsed=Number(e.data.elapsed)||0;if(ready&&(changed||!synced)){applyState();synced=true;}});
const status=document.getElementById('status');
try{
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x07111b,0);document.body.prepend(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,1000);scene.add(new THREE.HemisphereLight(0xe4f4ff,0x142b38,1.8));const key=new THREE.DirectionalLight(0xffffff,2.3);key.position.set(65,110,70);scene.add(key);const rim=new THREE.DirectionalLight(0x18dcb9,.6);rim.position.set(-50,20,-70);scene.add(rim);
 const groundMat=new THREE.MeshStandardMaterial({color:0x19313a,roughness:.9,side:THREE.DoubleSide,transparent:true});
 function floor(w,d,x,z,material=groundMat){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,d),material);p.rotation.x=-Math.PI/2;p.position.set(x,-.15,z);scene.add(p);return p;}
 floor(48,160,-56,0,groundMat.clone());floor(48,160,56,0,groundMat.clone());floor(64,40,0,-60,groundMat.clone());const lid=floor(64,120,0,20);const grid=new THREE.GridHelper(160,32,0x18dcb9,0x284554);grid.position.y=.01;scene.add(grid);
 const opening=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(64,.1,80)),new THREE.LineBasicMaterial({color:0x18dcb9,transparent:true,opacity:0}));scene.add(opening);
 const model=await new FBXLoader().loadAsync('assets/building.fbx');model.rotation.x=-Math.PI/2;model.updateMatrixWorld(true);const center=new THREE.Box3().setFromObject(model).getCenter(new THREE.Vector3());model.position.x=-center.x;model.position.z=-center.z;model.updateMatrixWorld(true);
 const materials=Object.fromEntries(Object.entries(palette).map(([id,color])=>[id,new THREE.MeshBasicMaterial({color})]));const structure=new THREE.MeshStandardMaterial({color:0x415965,roughness:.8}),basement=new THREE.MeshStandardMaterial({color:0x28675f,roughness:.7});const floors=new Map(),units=[],outlines=[];let meshes=0,basements=0;
 model.traverse(o=>{if(!o.isMesh)return;meshes++;const m=o.name.match(/^(R\d+)_.*_U(\d{2})(?:_|$)/),id=m?'U'+m[2]:null,under=o.name.startsWith('BASEMENT');if(under)basements++;o.material=materials[id]|| (under?basement:structure);if(id){o.userData.unitId=id;units.push(o);if(!floors.has(m[1]))floors.set(m[1],new Set());floors.get(m[1]).add(id);}});
 if(floors.size!==12||[...floors.values()].some(s=>s.size!==9))throw Error('Expected 12 residential model layers with 9 units each');
 for(const o of units){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,30),new THREE.LineBasicMaterial({color:0x081621,transparent:true,opacity:.6}));o.add(edge);outlines.push({edge,floor:o.name.split('_')[0]});const shade=new THREE.Mesh(o.geometry,new THREE.MeshStandardMaterial({color:0x1c3040,transparent:true,opacity:.15,roughness:.8,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));o.add(shade);}
 scene.add(model);document.body.dataset.unitFloors=JSON.stringify(Object.fromEntries([...floors].map(([f,ids])=>[f,[...ids].sort()])));document.body.dataset.unitPalette=JSON.stringify(palette);document.body.dataset.coloredUnitMeshes=units.length;window.getUnitColorSnapshot=()=>units.map(o=>({name:o.name,id:o.userData.unitId,color:'#'+o.material.color.getHexString()}));
 const marker=new THREE.Mesh(new THREE.TorusGeometry(5,.25,10,64),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0}));marker.position.set(12,34,0);scene.add(marker);
 const style=document.createElement('style');style.textContent='.unit-title{position:absolute;right:2%;top:40%;width:23%;font-size:25px;line-height:1.3}.unit-title small{display:block;font-size:17px;margin-top:6px;color:#b4c9d4}.unit-label{position:absolute;transform:translate(-50%,-50%);background:#061420ee;padding:2px 3px;color:white;font:bold 15px Arial;border:1px solid #7893a3;border-radius:3px}.unit-legend{position:absolute;left:3%;bottom:55px;display:flex;gap:20px;color:#e8f0f4;font:20px Arial}.unit-legend span{display:flex;gap:6px;align-items:center}.unit-legend i{width:16px;height:16px;border-radius:3px}.unit-summary{position:absolute;right:2%;bottom:60px;width:23%;font-size:15px;color:#b4c9d4}.scene-state{position:absolute;right:2%;top:28px;width:23%;font-size:28px;line-height:1.5}.scene-state small{display:block;font-size:18px;color:#a7c1cf;margin-top:12px}#hint{font-size:18px;max-width:66%}#status{font-size:17px;max-width:90%;bottom:4px}.model-divider{position:absolute;right:27%;top:25px;bottom:100px;border-right:1px solid #abc9d222}';document.head.appendChild(style);
 const title=document.createElement('div');title.className='unit-title';document.body.appendChild(title);const summary=document.createElement('div');summary.className='unit-summary';summary.textContent='原模型戶別分布 · 非室內格局圖';document.body.appendChild(summary);const stateLabel=document.createElement('div');stateLabel.className='scene-state';document.body.appendChild(stateLabel);const legend=document.createElement('div');legend.className='unit-legend';legend.innerHTML=Object.entries(palette).map(([id,color])=>`<span><i style="background:${color}"></i>${id}</span>`).join('');document.body.appendChild(legend);const divider=document.createElement('div');divider.className='model-divider';document.body.appendChild(divider);
 const planScene=new THREE.Scene(),planCamera=new THREE.OrthographicCamera(),planBounds=new THREE.Box3();let prefix='',labels=[];
 function plan(){const next=['R02','R06','R06'][segment];if(next===prefix)return;prefix=next;for(const o of [...planScene.children]){planScene.remove(o);o.geometry.dispose();o.material.dispose();}labels.forEach(l=>l.el.remove());labels=[];planBounds.makeEmpty();const unitBounds=new Map();
  model.traverse(o=>{if(!o.isMesh||!o.name.startsWith(prefix+'_'))return;const m=o.name.match(/_U(\d{2})(?:_|$)/),id=m?'U'+m[1]:null,geo=o.geometry.clone().applyMatrix4(o.matrixWorld);planScene.add(new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color:palette[id]||0x263d4d,side:THREE.DoubleSide})));if(id){geo.computeBoundingBox();if(!unitBounds.has(id))unitBounds.set(id,new THREE.Box3());unitBounds.get(id).union(geo.boundingBox);planBounds.union(geo.boundingBox);}});
  [...unitBounds].sort().forEach(([id,b])=>{const el=document.createElement('div');el.className='unit-label';el.textContent=id;el.dataset.unit=id;el.style.borderColor=palette[id];document.body.appendChild(el);labels.push({el,point:b.getCenter(new THREE.Vector3())});});document.body.dataset.unitCount=labels.length;document.body.dataset.unitIds=labels.map(l=>l.el.textContent).join(',');
 }
 let first=true,targetPos=new THREE.Vector3(),targetLook=new THREE.Vector3(),look=new THREE.Vector3(),cut=0;
 applyState=()=>{plan();cut=segment===2?1:0;const angle=[.84,1.07,1.1][segment],distance=[142,126,155][segment];targetPos.set(Math.sin(angle)*distance,cut?58:72,Math.cos(angle)*distance);targetLook.set(0,cut?24:34,0);if(first){camera.position.copy(targetPos);look.copy(targetLook);lid.material.opacity=1-cut;first=false;}outlines.forEach(({edge,floor})=>{edge.material.color.set(floor===prefix&&segment>0?0xffffff:0x081621);edge.material.opacity=floor===prefix&&segment>0?.9:.6;});title.innerHTML=`單層 9 戶<small>模型分層 ${prefix} · U01–U09</small>`;stateLabel.innerHTML=['全棟九戶配色<small>12 個住宅模型分層<br>同戶別，跨樓層同色</small>','P-01｜待確認<small>設備定位示意<br>模型分層 R06</small>','P-01｜紀錄已留存<small>09/06 14:20｜展示情境<br>地下室開口展示</small>'][segment];document.getElementById('hint').textContent=cut?'地面 GL ±0 ／ 地下量體開口展示':'地面 GL ±0 ／ 地上建築';status.textContent='展示情境資料 · 設備位置示意 · 戶別色不代表設備狀態';document.body.dataset.segment=segment;};
 ready=true;applyState();document.body.dataset.ready='true';document.body.dataset.meshes=meshes;document.body.dataset.basements=basements;parent.postMessage({type:'anlb-model-ready'},location.origin);
 let last=0;
 function render(now){const dt=Math.min((now-last)/1000,.05);last=now;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,a=reduced?1:1-Math.exp(-dt*4);camera.position.lerp(targetPos,a);look.lerp(targetLook,a);camera.lookAt(look);if(playing&&!reduced)camera.rotateY(Math.sin(elapsed*.1)*.012);lid.material.opacity=THREE.MathUtils.lerp(lid.material.opacity,1-cut,a);lid.visible=lid.material.opacity>.005;grid.visible=lid.material.opacity>.5;opening.material.opacity=1-lid.material.opacity;marker.material.opacity=THREE.MathUtils.lerp(marker.material.opacity,segment>0?.9:0,a);
  renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);renderer.clear();const w=innerWidth*.72,h=innerHeight-80;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setScissorTest(true);renderer.setViewport(0,80,w,h);renderer.setScissor(0,80,w,h);renderer.render(scene,camera);
  const px=innerWidth*.76,py=110,pw=innerWidth*.22,ph=innerHeight*.35,size=planBounds.getSize(new THREE.Vector3()),c=planBounds.getCenter(new THREE.Vector3()),hh=Math.max(size.z*1.18/2,size.x*1.15/(pw/ph)/2);planCamera.left=-hh*pw/ph;planCamera.right=hh*pw/ph;planCamera.top=hh;planCamera.bottom=-hh;planCamera.near=.1;planCamera.far=500;planCamera.position.set(c.x,200,c.z);planCamera.up.set(0,0,-1);planCamera.lookAt(c);planCamera.updateProjectionMatrix();planCamera.updateMatrixWorld();renderer.setViewport(px,py,pw,ph);renderer.setScissor(px,py,pw,ph);renderer.clearDepth();renderer.render(planScene,planCamera);renderer.setScissorTest(false);for(const l of labels){const p=l.point.clone().project(planCamera);l.el.style.left=px+(p.x+1)*pw/2+(l.el.dataset.unit==='U01'?9:l.el.dataset.unit==='U02'?-9:0)+'px';l.el.style.top=innerHeight-py-(p.y+1)*ph/2+'px';}requestAnimationFrame(render);
 }requestAnimationFrame(render);addEventListener('resize',()=>renderer.setSize(innerWidth,innerHeight));renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status.className='error';status.textContent='3D 顯示中斷，請重新載入此頁';});
}catch(error){document.body.dataset.error='true';status.className='error';status.textContent='模型無法顯示，請確認 WebGL 與模型檔案；未顯示替代模型。';parent.postMessage({type:'anlb-model-error'},location.origin);console.error(error);}
