import * as THREE from 'three';
import {FBXLoader} from 'three/addons/loaders/FBXLoader.js';
import './scoring.js';
const role=new URLSearchParams(location.search).get('role')||'exhibit',isExhibit=role==='exhibit',isDetail=role==='detail',status=document.getElementById('model-status'),label=document.getElementById('scene-label');
let state={segment:0,elapsed:0,playing:false},received=performance.now(),ready=false,applyScene=()=>{};
addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='anlb-scene')return;const old=state.segment;state={segment:Math.max(0,Math.min(isExhibit?2:3,e.data.segment||0)),elapsed:e.data.elapsed||0,playing:!!e.data.playing};received=performance.now();if(ready)applyScene(old!==state.segment);});
try{
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x07111b,1);renderer.shadowMap.enabled=isExhibit;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(isDetail?38:34,innerWidth/innerHeight,.1,1000);scene.add(new THREE.HemisphereLight(0xdbedff,0x1a303e,1.8));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(70,110,50);scene.add(key);key.castShadow=isExhibit;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-65,right:65,top:85,bottom:-50,near:1,far:250});key.shadow.bias=-.001;const rim=new THREE.DirectionalLight(isExhibit?0x3fb4f0:0x18dcb9,.7);rim.position.set(-70,40,-50);scene.add(rim);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(160,160),new THREE.MeshStandardMaterial({color:0x142b39,roughness:.9,metalness:.1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.15;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(160,32,0x335e71,0x183645);grid.position.y=.01;grid.visible=!isExhibit;scene.add(grid);if(isDetail){floor.visible=false;grid.visible=false;}
 const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(33,35,1.1,80),new THREE.MeshStandardMaterial({color:0x173748,metalness:.3,roughness:.6}));pedestal.position.y=-.8;scene.add(pedestal);pedestal.visible=!isDetail;
 const model=await new FBXLoader().loadAsync('assets/building.fbx');model.rotation.x=-Math.PI/2;model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(model),center=bounds.getCenter(new THREE.Vector3());model.position.x=-center.x;model.position.z=-center.z;model.updateMatrixWorld(true);scene.add(model);
 const objects=[],units=[],unitIndex=new Map(),worldBox=new THREE.Box3(),tmp=new THREE.Vector3();let meshCount=0;
 model.traverse(o=>{if(!o.isMesh)return;meshCount++;o.castShadow=true;o.receiveShadow=true;const match=o.name.match(/^(R\d+)_.*_U(\d{2})(?:_|$)/),id=match?`${match[1]}-U${match[2]}`:null;
  const material=id&&!isExhibit?new THREE.MeshBasicMaterial({color:0x24c8a5}):new THREE.MeshStandardMaterial({color:id?0xd1e2eb:0x648390,roughness:.57,metalness:.14,transparent:!!id,opacity:1});o.material=material;o.userData.basePosition=o.position.clone();o.userData.id=id;o.userData.floor=o.name.match(/^R\d+/)?.[0];worldBox.setFromObject(o);const c=worldBox.getCenter(new THREE.Vector3());const direction=new THREE.Vector3(c.x,0,c.z).normalize().multiplyScalar(2.1);direction.applyQuaternion(o.parent.getWorldQuaternion(new THREE.Quaternion()).invert());o.userData.separate=direction;objects.push(o);if(id){units.push(o);unitIndex.set(id,o);}
 });
 if(units.length!==108)throw Error(`Expected 108 unit meshes; got ${units.length}`);
 for(const o of units){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(o.geometry,30),new THREE.LineBasicMaterial({color:0x173040,transparent:true,opacity:.7}));o.add(edge);o.userData.edge=edge;}
 const weather=new THREE.Group();scene.add(weather);const sun=new THREE.Mesh(new THREE.SphereGeometry(5,24,16),new THREE.MeshBasicMaterial({color:0xffd174}));sun.position.set(35,70,12);weather.add(sun);const sunRing=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:64},(_,i)=>new THREE.Vector3(Math.cos(i*Math.PI/32)*7.3,Math.sin(i*Math.PI/32)*7.3,0))),new THREE.LineBasicMaterial({color:0xffd174,transparent:true,opacity:.35}));sun.add(sunRing);
 const rainPositions=new Float32Array(180*6);for(let i=0;i<180;i++){const x=18+(i*7%23),y=15+(i*13%76),z=-30+(i*17%65);rainPositions.set([x,y,z,x-.4,y-2.2,z],i*6);}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPositions,3));const rain=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:0x8ed3f1,transparent:true,opacity:.6}));weather.add(rain);
 const flow=new THREE.Group();for(let i=0;i<5;i++){const pts=Array.from({length:40},(_,j)=>new THREE.Vector3(-48+j*2.4,18+i*8+Math.sin(j*.15)*3,Math.sin(j*.12+i)*20));const g=new THREE.BufferGeometry().setFromPoints(pts),l=new THREE.Line(g,new THREE.LineDashedMaterial({color:0x83dfd1,dashSize:3,gapSize:3,transparent:true,opacity:.65}));l.computeLineDistances();flow.add(l);}weather.add(flow);
 const sparkPositions=new Float32Array(80*3);for(let i=0;i<80;i++)sparkPositions.set([-9+(i*11%20),8+(i*7%50),-21+(i*13%43)],i*3);const sparkGeo=new THREE.BufferGeometry();sparkGeo.setAttribute('position',new THREE.BufferAttribute(sparkPositions,3));const sparks=new THREE.Points(sparkGeo,new THREE.PointsMaterial({color:0xffdc8d,size:.55,transparent:true,opacity:.9}));weather.add(sparks);weather.visible=!isDetail&&!isExhibit;
 let first=true,targetPosition=new THREE.Vector3(),targetLook=new THREE.Vector3(),look=new THREE.Vector3(),selected=[],entryTime=performance.now();
 applyScene=(changed)=>{const seg=state.segment;entryTime=changed?performance.now():entryTime;selected=isExhibit?['R06-U01','R06-U08']:BOS.metrics[seg].pair;
  const angle=isExhibit?[.7,1.25,2.05][seg]:[.95,2.25,3.35,4.45][seg];targetLook.set(0,isExhibit?30:33,0);let distance=isExhibit?150:150,height=isExhibit?78:82;
  if(isDetail){const box=new THREE.Box3();for(const id of selected){const o=unitIndex.get(id);if(o)box.union(new THREE.Box3().setFromObject(o));}box.getCenter(targetLook);distance=75;height=targetLook.y+37;}
  targetPosition.set(targetLook.x+Math.sin(angle)*distance,height,targetLook.z+Math.cos(angle)*distance);if(first){camera.position.copy(targetPosition);look.copy(targetLook);first=false;}
  objects.forEach(o=>{o.visible=!isDetail||o.userData.floor===selected[0].split('-')[0];if(o.name.startsWith('BASEMENT'))o.visible=false;});
  units.forEach(o=>{o.userData.edge.material.color.set(selected.includes(o.userData.id)&&!isExhibit?0xffffff:0x173040);o.userData.edge.material.opacity=selected.includes(o.userData.id)?1:.65;});
  sun.visible=seg===0;rain.visible=seg===1;flow.visible=seg===2;sparks.visible=seg===3;key.color.set(!isExhibit&&seg===3?0x849ebc:0xffffff);key.intensity=!isExhibit&&seg===3?1.5:2.5;
  label.textContent=isExhibit?['完整建築量體','樓板與核心筒','同層九戶 · 輕微分離'][seg]:isDetail?'同戶局部對照':`${BOS.metrics[seg].name}情境 · ${['示意日照','示意降雨','通風流線','日夜用電'][seg]}`;
  status.textContent=isExhibit?'':isDetail?selected.join(' ／ '):'模型戶別著色＝展示情境分數 · 天氣非熱工預測';if(isExhibit)label.textContent='';document.body.dataset.segment=seg;document.body.dataset.selected=selected.join(',');
 };
 ready=true;applyScene(true);document.body.dataset.ready='true';document.body.dataset.meshes=meshCount;document.body.dataset.unitCount=units.length;document.body.dataset.role=role;
 window.modelSnapshot=()=>({segment:state.segment,selected,units:units.map(o=>({id:o.userData.id,color:'#'+o.material.color.getHexString(),score:o.userData.score??null,visible:o.visible})),camera:camera.position.toArray()});parent.postMessage({type:'anlb-model-ready'},location.origin);
 let last=0,lastColors=0,snap=null;
 function render(now){const dt=Math.min((now-last)/1000,.05);last=now;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,t=Math.min(isExhibit?12:18,state.elapsed+(state.playing?(now-received)/1000:0)),blend=reduced?1:1-Math.exp(-dt*4.5);camera.position.lerp(targetPosition,blend);look.lerp(targetLook,blend);camera.lookAt(look);
  if(!isExhibit&&now-lastColors>100){snap=BOS.snapshot(state.segment,reduced?18:t);for(const r of snap.records){const o=unitIndex.get(r.id);o.userData.targetColor=new THREE.Color(r.color);o.userData.score=r.score;}lastColors=now;document.body.dataset.phase=snap.phase;}
  for(const o of units){if(isExhibit){const opacity=state.segment===1?.15:1;o.material.opacity=THREE.MathUtils.lerp(o.material.opacity,opacity,blend);o.material.depthWrite=o.material.opacity>.95;const amount=state.segment===2&&o.userData.floor==='R06'?(reduced?.5:Math.sin(Math.min(1,t/12)*Math.PI)):0;tmp.copy(o.userData.basePosition).addScaledVector(o.userData.separate,amount);o.position.lerp(tmp,blend);}else if(o.userData.targetColor){if(reduced||t>=14||!state.playing&&now-entryTime>600)o.material.color.copy(o.userData.targetColor);else o.material.color.lerp(o.userData.targetColor,1-Math.exp(-dt*10));}}
  if(!isDetail&&!isExhibit){sun.position.set(35+Math.sin(t*.17)*9,70+Math.cos(t*.17)*3,8);rain.position.y=!reduced?-(t*8%13):0;flow.position.x=!reduced?Math.sin(t)*2:0;sparks.material.opacity=!reduced?.65+Math.sin(t)*.15:.8;}
  camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.render(scene,camera);requestAnimationFrame(render);
 }requestAnimationFrame(render);addEventListener('resize',()=>renderer.setSize(innerWidth,innerHeight));renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status.className='error';status.textContent='3D 顯示中斷，請重新整理。';});
}catch(error){document.body.dataset.error='true';status.className='error';status.textContent='模型無法顯示；請確認 WebGL 與模型檔案。未使用替代模型。';parent.postMessage({type:'anlb-model-error'},location.origin);console.error(error);}
