/* Four-panel motion restoration. Uses the existing shared exhibition clock. */
const stillTracks=maintenanceTracks,stillRecord=maintenanceRecord;
maintenanceTracks=function(seg){return stillTracks(seg).replace('maintenance-tracks beat-', 'maintenance-tracks motion-tracks beat-').replace(/<div class="track-rail"><\/div>/g,'<div class="track-rail"></div><div class="track-progress"></div>').replace(/<i class="track-node ([^"]*)" style="left:([^;]+);--n:(\d)">/g,(_,cl,left,n)=>`<i class="track-node ${cl}" data-track-node="${n}" style="left:${8+28*Number(n)}%;--n:${n}">`);};
maintenanceRecord=function(seg){return stillRecord(seg).replace('class="review-record"',`class="review-record motion-record record-beat-${seg}"`).replace('<header>','<header data-key="record-identity">').replace('class="record-fields ', 'data-key="record-work" class="record-fields ').replace('class="record-index ', 'data-key="record-index" class="record-index ');};
responsibility=function(seg){return artSVG('住戶、物業與專業廠商的維養接力',`<g class="motion-relay" data-beat="${seg}"><path class="relay-base" d="M255 525H1415"/>${[['manager','住戶','日常清潔'],['handover','物業','公區維養安排'],['tools','專業廠商','設備檢修']].map(([ic,t,d],i)=>`<g data-relay-role="${i}">${pic(ic,160+i*580,0,190)}${tx(255+i*580,290,t,'large','middle')}${tx(255+i*580,352,d,'','middle')}<path class="relay-drop" d="M${255+i*580} 380V475"/>${pic('record',205+i*580,475,100)}</g>`).join('')}<g class="relay-handoff" data-relay-link="0">${pic('handover',485,55,120)}<path pathLength="1" d="M365 150H705"/></g><g class="relay-handoff" data-relay-link="1">${pic('handover',1065,55,120)}<path pathLength="1" d="M945 150H1285"/></g><g class="relay-packet">${pic('record',-42,475,84)}</g></g>`);};
systemRoute=function(seg){return artSVG('沿上游、泵浦及下游支路連通',`<g class="motion-route" data-beat="${seg}"><path class="route-base" d="M370 275H690M940 275H1090V145H1310M1090 275V430H1310"/><path class="route-reveal" data-route="0" pathLength="1" d="M370 275H690"/><path class="route-reveal" data-route="1" pathLength="1" d="M940 275H1090V145H1310"/><path class="route-reveal" data-route="2" pathLength="1" d="M1090 275V430H1310"/><g data-route-node="0">${pic('water',110,155,230)}${tx(225,485,'給水來源','large','middle')}</g><g data-route-node="1">${pic('pipe',690,155,240)}${tx(810,485,'P-01','large','middle')}</g><g data-route-node="2">${pic('layers',1340,30,170)}${tx(1425,265,'給水支路 A','','middle')}</g><g data-route-node="3">${pic('layers',1340,320,170)}${tx(1425,555,'給水支路 B','','middle')}</g><circle class="route-focus" cx="810" cy="275" r="142"/><circle class="route-packet" r="9"/></g>`);};
const motionClamp=v=>Math.max(0,Math.min(1,v));
let motionKey=null,motionChanged=0,motionManual=false;
function updateReviewMotion(now){requestAnimationFrame(updateReviewMotion);const st=globalThis.showcaseState;if(!st||document.hidden)return;const key=st.mode+':'+st.segment+':'+st.scenarioSeed;const first=motionKey===null;if(key!==motionKey){motionChanged=now;motionManual=!first&&!st.playing&&st.elapsed<.1;motionKey=key;}
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(st.playing)motionManual=false;
 const elapsed=st.elapsed+(st.playing?(now-st.received)/1000:0);
 // A paused manual change completes one reveal; a frozen/reconnected result stays put.
 const t=reduced?12:(motionManual&&!st.playing?Math.max(st.elapsed,(now-motionChanged)/1000*4):elapsed);
 document.querySelectorAll('.motion-tracks').forEach(root=>{root.querySelectorAll('.maintenance-tracks>section').forEach((row,i)=>{const local=motionClamp((t-.65-i*.28)/3.2),p=(Math.min(2,st.segment)+local)/3;row.style.setProperty('--track-progress',p);row.querySelectorAll('[data-track-node]').forEach((node,n)=>{const q=motionClamp((p*3-n)*5+1);node.style.opacity=String(.22+.78*q);node.style.transform=`translate(-50%,-50%) scale(${.86+.14*q})`;});});});
 document.querySelectorAll('.motion-record').forEach(root=>{const p=motionClamp((t-.3)/1.8);root.style.setProperty('--record-open',st.segment===0?0:st.segment===2?1:p);root.style.setProperty('--record-save',st.segment===2?motionClamp((t-2)/1.2):0);});
 document.querySelectorAll('.motion-relay').forEach(root=>{const beat=+root.dataset.beat,p=motionClamp((t-.6)/2.5);root.querySelectorAll('[data-relay-role]').forEach((el,i)=>el.style.opacity=String(i<beat?.65:i===beat?.3+.7*p:.18));root.querySelectorAll('[data-relay-link]').forEach((el,i)=>{const v=i<beat-1?1:i===beat-1?p:0;el.style.opacity=String(v);el.querySelector('path[pathLength]').style.strokeDashoffset=String(1-v);});const x=beat===0?255:255+(beat-1+p)*580;root.querySelector('.relay-packet').setAttribute('transform',`translate(${x} 0)`);root.querySelector('.relay-packet').style.opacity=String(beat>0&&p>0&&p<1?1:0);});
 document.querySelectorAll('.motion-route').forEach(root=>{const beat=+root.dataset.beat;root.querySelectorAll('[data-route]').forEach((el,i)=>{const p=beat===0?0:motionClamp((t-.3-i*.8)/1.1);el.style.strokeDashoffset=String(1-p);el.style.opacity=String(beat===2&&i===2?.25:1);});root.querySelectorAll('[data-route-node]').forEach((el,i)=>el.style.opacity=String(i===0?1:beat===0?.2:.2+.8*motionClamp((t-.7-(i-1)*.8)/1.1)));root.querySelector('.route-focus').style.opacity=String(beat===2?motionClamp((t-2)/.8):0);const path=root.querySelector('[data-route="0"]'),p=path.getPointAtLength(path.getTotalLength()*motionClamp((t-2.5)/2));const dot=root.querySelector('.route-packet');dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.style.opacity=String(beat===2&&t<4.5?1:0);});
}
requestAnimationFrame(updateReviewMotion);
