STORY.data=BOS.metrics.map((m,i)=>({title:m.title,sub:`WELL FM｜${m.name}觀察 · 展示情境分數`,steps:['建立指標','情境演變','同步比較'],d:m.name,detail:[m.target,m.rule,m.source]}));
MODES.forEach(m=>{Object.assign(m,CHAPTERS[m.id]);m.segments=STORY[m.id].map(s=>s.title.replace(/\n/g,'，'));m.cues=STORY[m.id].map((s,i)=>m.id==='data'?`第 ${i+1} 段 ${BOS.metrics[i].name}：左側 A 看天氣與逐戶顏色，右側 D 看同戶讀值和評分依據。分數是展示設定，不是認證。`:`${s.sub} ${m.id==='idle'?'A 講耐震主張，B 是品牌宣言，D 是全景模型。':'D 是 WELL FM 總覽，S2／S3 分別展示關聯與紀錄。'}`);});
const REV_TITLES={life:{c:'建築的紀錄，持續累積',d:'WELL FM｜履歷總覽',s1:'建材查驗',s2:'證據對照',s3:'維修紀錄',s4:'管理交接'},bim:{c:'從整體，找到位置',d:'WELL FM｜設備總覽',s1:'樓層索引',s2:'設備關係',s3:'關聯文件',s4:'管線透視'}};
const REV_CAPTIONS={life:{c:['建造有依據','資料一起交付','維養持續累積'],d:['設備建檔與文件分類','交付文件與設備連結','維養結果持續留存'],s1:['材料分類','查驗部位放大','對應檢驗依據'],s2:['建造文件留存','交付資料對照','依項目回查'],s3:['先讀設備資料','展開檢查內容','留下處理結果'],s4:['建造方留下紀錄','交付方接收資料','維養方持續接力']},bim:{c:['全棟範圍','指定區域','設備位置'],d:['找到同一設備','讀取所屬系統','查閱最近紀錄'],s1:['選定 L06','保留樓層位置','對應東側設備區'],s2:['先選給水系統','展開關聯設備','定位 P-01'],s3:['展開文件索引','連到檢查文件','讀取維養紀錄'],s4:['牆體外層遮蔽','牆內管線顯露','路徑連到設備']}};
function revSVG(kind,body){return `<svg class="unique-svg" data-viz="${kind}" viewBox="0 0 1400 500" role="img" aria-label="${kind} 展示概念圖">${body}</svg>`;}
function revGraph(kind,seg){
 if(kind==='radial'||kind==='triad'){const labels=kind==='triad'?['安全','品質','維養']:['建造依據','交付資料','維養累積'],points=[[260,330],[700,90],[1140,330]];return revSVG(kind,`<circle class="orbit" cx="700" cy="275" r="175"/><text class="center-word" x="700" y="285" text-anchor="middle">${kind==='triad'?'建築承諾':'生命履歷'}</text>${points.map(([x,y],i)=>`<path class="radial-link ${i<=seg?'lit':''}" d="M700 275L${x} ${y}"/><g class="node ${i===seg?'active':''}"><circle cx="${x}" cy="${y}" r="76"/><text x="${x}" y="${y+12}" text-anchor="middle">${labels[i]}</text></g>`).join('')}`);}
 if(kind==='material')return revSVG(kind,`${[0,1,2].map((n)=>`<g class="material-layer ${n===seg?'active':''}" style="--layer:${n}"><path d="M100 ${145+n*75}L360 ${65+n*75}L615 ${145+n*75}L355 ${230+n*75}Z"/><text x="80" y="${165+n*75}">${['表層','基層','結構'][n]}</text></g>`).join('')}<path class="detail-wire" d="M620 250H770"/><circle class="magnifier" cx="985" cy="240" r="175"/>${[0,1,2,3,4].map(i=>`<path class="hatch" d="M${865+i*55} 115V365"/>`).join('')}<text x="985" y="470" text-anchor="middle">${['材料分類示意','局部查驗視窗','檢驗文件可回查'][seg]}</text>`);
 if(kind==='floor')return revSVG(kind,`${Array.from({length:8},(_,n)=>`<g class="floor-level ${n===2?'active':''}"><rect x="160" y="${20+n*54}" width="620" height="42" rx="4"/><text x="190" y="${50+n*54}">L${String(8-n).padStart(2,'0')}</text></g>`).join('')}<path class="floor-cursor" d="M900 55V415M840 151H1040"/><text x="960" y="230">L06</text><text x="960" y="290">${seg===0?'樓層已選定':seg===1?'位置保留':'東側設備區'}</text>`);
 if(kind==='nested')return revSVG(kind,`<g class="space-zoom zoom-${seg}"><rect class="outer-space" x="70" y="30" width="1150" height="420" rx="20"/><text x="100" y="90">全棟</text><rect class="middle-space" x="360" y="130" width="650" height="275" rx="15"/><text x="385" y="187">L06 · 東側設備區</text><rect class="inner-space" x="680" y="240" width="245" height="125" rx="12"/><text x="800" y="315" text-anchor="middle">P-01</text></g><path class="view-guide" d="M1240 30h60v420h-60"/>`);
 if(kind==='topology'){const pts=[[190,250,'給水系統'],[540,110,'P-01'],[540,380,'P-02'],[920,100,'感測訊號'],[1170,280,'維養紀錄'],[920,405,'設備文件']];return revSVG(kind,`<g class="topology phase-${seg}"><path class="network-cables" d="M190 250L540 110L920 100L1170 280L920 405L540 110M190 250L540 380"/>${pts.map(([x,y,t],i)=>`<g class="node ${i===[0,4,1][seg]?'active':''}"><circle cx="${x}" cy="${y}" r="65"/><text x="${x}" y="${y+12}" text-anchor="middle">${t}</text></g>`).join('')}</g>`);}
 if(kind==='relations')return revSVG(kind,`<rect class="identity" x="80" y="170" width="300" height="155" rx="20"/><text class="large-svg" x="230" y="265" text-anchor="middle">P-01</text>${['文件索引','檢查文件','維養紀錄'].map((t,i)=>`<path class="relation ${i<=seg?'lit':''}" d="M380 245C640 245 640 ${90+i*155} 900 ${90+i*155}"/><g class="doc-node ${i===seg?'active':''}"><rect x="900" y="${30+i*155}" width="390" height="115" rx="12"/><text x="1095" y="${100+i*155}" text-anchor="middle">${t}</text></g>`).join('')}`);
 if(kind==='section')return revSVG(kind,`<g class="pipe-cut phase-${seg}"><rect class="wall-core" x="120" y="65" width="1080" height="360" rx="12"/><path class="inside-pipe" d="M220 330H490V160H850V300H1090"/><path class="water-motion" d="M220 330H490V160H850V300H1090"/><rect class="wall-cover" x="120" y="65" width="1080" height="360" rx="12"/><circle class="pipe-device" cx="1090" cy="300" r="45"/></g><text x="120" y="485">${['外層遮蔽｜管線概念剖面','揭開外層｜給水路徑','P-01｜與設備位置連結'][seg]}</text>`);
 if(kind==='relay')return revSVG(kind,`<text x="80" y="100">管理者</text><text x="80" y="360">建築紀錄</text><path class="relay-track" d="M320 80H1240M320 340H1240"/>${['建造方','交付方','維養方'].map((t,i)=>`<g class="relay-person ${i===seg?'active':''}"><circle cx="${400+i*380}" cy="80" r="48"/><text x="${400+i*380}" y="180" text-anchor="middle">${t}</text></g><path class="relay-drop ${i<=seg?'lit':''}" d="M${400+i*380} 210V340"/><rect class="relay-record ${i<=seg?'active':''}" x="${350+i*380}" y="290" width="100" height="100" rx="12"/>`).join('')}<text x="780" y="470" text-anchor="middle">人員交接，紀錄不中斷</text>`);
 if(kind==='structure')return revSVG(kind,`<g class="structure-sequence step-${seg}"><path class="columns" d="M360 440V70M700 440V70M1040 440V70"/><path class="beams" d="M300 110H1100M300 270H1100"/><path class="slabs" d="M260 440H1140M290 285H1110M290 125H1110"/></g><text x="700" y="490" text-anchor="middle">${['柱｜垂直支撐','樑｜水平連結','樓板｜空間承載'][seg]} · 結構概念示意</text>`);
 if(kind==='verification')return revSVG(kind,`<rect class="document-sheet" x="310" y="20" width="780" height="440" rx="16"/><text class="large-svg" x="390" y="100">SGS · 檢驗紀錄</text>${['項目與文件','查驗留存','驗證依據'].map((t,i)=>`<text x="390" y="${200+i*90}">${t}</text><path class="verify-tick ${i<=seg?'lit':''}" d="m880 ${182+i*90} 28 30 65-66"/>`).join('')}`);
 if(kind==='information')return revSVG(kind,`<rect class="info-core" x="80" y="165" width="300" height="165" rx="18"/><text x="230" y="260" text-anchor="middle">同一份資訊</text>${['建造','交付','維養'].map((t,i)=>`<path class="info-link ${i<=seg?'lit':''}" d="M380 250C700 250 600 ${90+i*165} 1000 ${90+i*165}"/><circle class="info-end ${i===seg?'active':''}" cx="1090" cy="${90+i*165}" r="64"/><text x="1090" y="${103+i*165}" text-anchor="middle">${t}</text>`).join('')}`);
 return revSVG('record-layers',`${['建築資訊','品質依據','維養紀錄'].map((t,i)=>`<g class="record-layer ${i<=seg?'active':''}" style="--layer:${i}"><rect x="${180+i*260}" y="${50+i*90}" width="500" height="200" rx="15"/><text x="${430+i*260}" y="${160+i*90}" text-anchor="middle">${t}</text></g>`).join('')}`);
}
function revMatrix(seg){return `<div class="evidence-matrix" data-viz="evidence-matrix"><span>文件／階段</span>${['建造','交付','回查'].map(t=>`<b>${t}</b>`).join('')}${['建材檢驗','工法查驗','設備文件'].map((t,r)=>`<strong>${t}</strong>${[0,1,2].map(c=>`<div class="evidence-cell ${c<=seg?'available':''} ${c===seg&&r===seg?'focus':''}"><span>${c<=seg?'●':'○'}</span><small>${c<=seg?'示例留存':'待展開'}</small></div>`).join('')}`).join('')}</div>`;}
function revReceipt(seg){return `<div class="repair-receipt" data-viz="repair-receipt"><header><span>WELL FM · P-01</span><b>維修紀錄</b></header><div class="receipt-columns"><section><small>處理前</small><strong>${['設備待查閱','例行檢查','檢查已完成'][seg]}</strong><p>給水設備 · 展示案例</p></section><section class="receipt-result"><small>處理後</small><strong>${['資料建檔','結果待留存','紀錄已留存'][seg]}</strong><p>${['設備資訊已整理','檢查內容展開','09/06 14:20'][seg]}</p></section></div><div class="receipt-stamp ${seg===2?'complete':''}">${seg===2?'已留存':'紀錄展開中'}</div></div>`;}
function revSummary(mode,seg){const data=mode==='life'?[[['設備摘要','P-01｜給水設備','建檔資料已整理'],['文件索引','檢驗／工法／設備','依分類查阅'],['近期紀錄','09/06｜建立履歷','展示情境']],[['設備摘要','P-01｜文件關聯','設備與交付資料'],['文件索引','交付文件／操作資料','對應設備查閱'],['近期紀錄','09/06｜資料交付','交接摘要']],[['設備摘要','P-01｜維養紀錄','持續累積'],['文件索引','檢查／保養／維修','原始依據保留'],['近期紀錄','09/06｜結果留存','10/06｜預定保養']]][seg]:[['設備身份','P-01｜給水設備','L06｜東側示例區域'],['所屬系統','給水系統','位置與關聯設備'],['最近紀錄',seg===0?'文件索引已建立':seg===1?'09/06｜檢查內容':'09/06｜維養留存','同一設備，持續追溯']];return `<div class="fm-concentrated" data-viz="${mode==='life'?'fm-digest':'fm-identity'}">${data.map(([title,a,b],i)=>`<section class="fm-block ${i===seg?'current':''}"><span>0${i+1} · ${title}</span><strong>${a}</strong><p>${b}</p></section>`).join('')}</div>`;}
function revFrame(id,cl,body,note='展示情境資料 · 非即時建物資料'){return `<article class="panel revision ${cl} ${portrait(id)?'portrait':''}" data-id="${id}" data-mode="${state.mode}" data-segment="${state.segment}"><div class="kv-background" aria-hidden="true"><i></i><i></i><i></i></div>${panelHeader(id)}<div class="panel-body">${body}</div>${foot(note)}</article>`;}
function scoreLegend(){return `<div class="score-legend" data-key="score-legend">${BOS.bands.map(b=>`<div><i style="background:${b.color}"></i><b>${b.min}–${b.max}</b><span>${b.label}</span></div>`).join('')}<div><i style="background:#677681"></i><span>資料不足</span></div></div>`;}
function scoreFrame(role){return `<div class="revision-model ${role}" data-key="model-${role}"><div class="model-loading">正在載入提供的建築模型…</div><iframe class="model-view" data-key="model-${role}" data-role="${role}" title="${role==='exhibit'?'建築全景量體':role==='hero'?'逐戶情境評分模型':'所選戶局部對照'}" src="${root}model-stage.html?role=${role}"></iframe></div>`;}
function scorePlot(s){const m=s.metric;return `<div class="criterion-chart" data-viz="criterion-${m.id}"><div class="criterion-rule"><strong>${m.target}</strong><span>${m.rule}</span></div>${targetBand(s)}${s.selected.map((r,i)=>`<div class="compare-row"><b>${r.id}</b><div class="compare-track ${m.id==='energy'?'energy-deviation':''}">${m.id==='energy'?'<em></em>':''}<i ${m.id==='energy'?'data-energy-deviation':'data-score-width'}="${r.id}" style="width:${r.score}%;background:${r.color}"></i>${m.id==='energy'?`<small data-energy-delta="${r.id}"></small>`:''}</div><strong data-score="${r.id}">${r.score}</strong></div>`).join('')}<div class="criterion-raw">${s.selected.map(r=>`<span>${r.id} <b data-value="${r.id}">${formatReading(r.value,m)}</b></span>`).join('')}</div></div>`;}
function formatReading(value,m){return value===null?'資料不足':`${value.toFixed(m.id==='energy'?3:m.id==='air'?0:1)} ${m.unit}`;}
function targetBand(s){const m=s.metric,[low,high]=m.id==='air'?[0,1480]:m.limits,targets=m.id==='temperature'?[24,26]:m.id==='humidity'?[30,50]:m.id==='air'?[0,400]:[s.baseline,s.baseline],left=(targets[0]-low)/(high-low)*100,width=(targets[1]-targets[0])/(high-low)*100;return `<div class="target-axis"><span>${low}</span><div class="target-track true-target"><i data-target-band style="left:${left}%;width:${Math.max(width,.5)}%"></i>${s.selected.map((r,i)=>`<b class="value-marker marker-${i}" data-marker="${r.id}" style="left:${Math.max(0,Math.min(100,((r.value??low)-(m.id==='air'?420:0)-low)/(high-low)*100))}%">${i+1}</b>`).join('')}</div><span>${high}</span></div><div class="axis-unit">${m.unit} · ${m.id==='energy'?'偏差棒 ±150%；白線＝中位數；右欄分數':m.id==='air'?'室內 − 室外（420 ppm，模擬）':'綠色區為本展示參考範圍'}</div>`;}
function revisionPanel(id){const m=current(),seg=state.segment,s=STORY[m.id][seg];
 if(id==='main')return `<article class="panel clean-main" data-id="main"><div class="image-only"><img src="${root}assets/${{idle:'tower',life:'orbit',bim:'aerial',data:'tower'}[m.id]}.png" alt="既有 UE 模型參考影像，非實拍"></div><div class="main-info"><span>0${MODES.indexOf(m)} · ${seg+1}/${m.segmentCount}</span><strong>${s.title.replace(/\n/g,'，')}</strong><img class="corner-logo" src="${root}assets/logo.png" alt="ANLB INSIDE"></div></article>`;
 if(id==='b'){const titles={idle:'第五代住宅宣言',life:'建築生命履歷',bim:'數位孿生定位',data:'建築 BOS\n真實數據匯流'},sub={idle:'AI 原生建築生命體',life:'每一次檢驗，都有紀錄',bim:'找到位置，也找到紀錄',data:'WELL FM｜從全棟訊號，看見每戶差異'};return revFrame(id,'chapter-definition',`${m.id==='idle'?`<img class="hero-logo" src="${root}assets/logo.png" alt="ANLB INSIDE">`:`<div class="chapter-number">0${MODES.indexOf(m)}</div>`}<h1>${lines(titles[m.id])}</h1><p>${sub[m.id]}</p><div class="chapter-keywords">${{idle:'全透明原生健康建築',life:'建造有依據 · 交付有資料 · 維養有紀錄',bim:'樓層 · 區域 · 設備 · 履歷',data:'溫度 · 濕度 · 空氣 · 用電'}[m.id]}</div>`,'品牌與章節主張 · 適用範圍依個案文件');}
 if(m.id==='data'){
  const snap=BOS.snapshot(seg,revisionElapsed(),state.scenarioSeed),metric=snap.metric;
  if(id==='a')return revFrame(id,'score-hero',`<div class="eyebrow">WELL FM · ${metric.name}觀察</div><h1>${metric.title}</h1>${scoreFrame('hero')}${scoreLegend()}<div class="scenario-phase" data-phase>${snap.phase}</div>`,'模擬天氣與戶別數據 · 非熱工預測 · 展示情境分數');
  if(id==='d')return revFrame(id,'score-explainer',`<div class="eyebrow">WELL FM · 評分依據</div><h1>${metric.name}，怎麼看？</h1><div class="explanation-area">${scorePlot(snap)}<p class="score-caveat">${metric.source}</p></div>${scoreFrame('detail')}<div class="detail-pair">同戶對照<br>${metric.pair.join(' ／ ')}</div>`,'0–100 分為展示算法 · 不加總為健康分數');
  if(id==='c')return revFrame(id,'score-principle',`<div class="eyebrow">BUILDING BOS · WELL FM</div><h1>同一組訊號<br>左右一起看</h1><div class="metric-ribbon">${BOS.metrics.map((x,i)=>`<div class="${i===seg?'active':''}"><span>0${i+1}</span><strong>${x.name}</strong></div>`).join('')}</div><p>${metric.target}</p><div class="principle-note">A 看情境與戶別顏色 · D 看標準與比較</div>`);
  if(id==='s5')return revFrame(id,'metric-index',`<h1>四項指標<br>逐戶看清</h1><div class="four-metrics">${BOS.metrics.map((x,i)=>`<section class="${i===seg?'active':''}"><span>0${i+1}</span><h2>${x.name}</h2><p>${x.unit}</p></section>`).join('')}</div>`,'WELL FM · 四項展示情境');
  if(id==='s6')return revFrame(id,'score-notes',`<h1>看懂分數<br>也看懂依據</h1><div class="score-note-list"><section><h2>資料來源</h2><p>模擬戶別讀值<br>非現場感測</p></section><section><h2>分數意義</h2><p>接近展示目標<br>不代表認證</p></section><section><h2>一致條件</h2><p>同一套判讀<br>逐戶可追溯</p></section></div>`,'四項各自評分 · 不產生健康總分');
  if(/^s[1-4]$/.test(id)){const n=Number(id[1])-1,title=['原始讀值','分數分布','同條件比較','資料追溯'][n];let plot;
   if(n===0)plot=`<div class="reading-bands" data-viz="raw-readings">${snap.selected.map(r=>`<section><span>${r.id}</span><strong data-value="${r.id}">${formatReading(r.value,metric)}</strong><p>${metric.id==='air'?'室外 420 ppm｜模擬':metric.id==='energy'?'同日 · 同入住條件':'展示情境讀值'}</p></section>`).join('')}</div>`;
   if(n===1)plot=`<div class="histogram" data-viz="distribution">${BOS.bands.map((b,i)=>`<section><strong data-count="${i}">${snap.histogram[i]}</strong><i data-hist="${i}" style="height:${snap.histogram[i]*2+8}px;background:${b.color}"></i><span>${b.min}–${b.max}</span></section>`).join('')}</div><div class="chart-note">108 個模型戶別 · <span data-missing>${snap.missing}</span> 戶資料不足</div>`;
   if(n===2)plot=`<div class="benchmark-chart" data-viz="benchmark"><div class="baseline-label">${metric.id==='energy'?'同條件中位數＝70 分':'目標範圍＝100 分'}</div>${snap.selected.map(r=>`<div class="benchmark-row"><b>${r.id}</b><div class="benchmark-track"><em style="left:${metric.id==='energy'?70:100}%"></em><i data-score-width="${r.id}" style="width:${r.score}%;background:${r.color}"></i></div><strong data-score="${r.id}">${r.score}</strong></div>`).join('')}<p>${metric.id==='energy'?'空置與缺面積戶不列入比較':'不同指標的分數不相加'}</p></div>`;
   if(n===3)plot=`<div class="audit-list" data-viz="audit"><div><b>01</b><span>示範資料</span><strong>2026/09/06</strong></div><div><b>02</b><span>${metric.name}算法</span><strong>獨立計分 · 0–100</strong></div><div><b>03</b><span>選戶與紀錄</span><strong>${metric.pair[0]}</strong></div></div>`;
   return revFrame(id,'unique-panel bos-lower',`<div class="eyebrow">WELL FM · ${metric.name}</div><h1>${title}</h1><div class="unique-art">${plot}</div><p class="unique-caption">${['先看數值，再看分數','每戶差異，一眼看見','比較條件，說清楚','從分數，回查依據'][n]}</p>`,metric.id==='energy'?'展示情境資料 · 能耗管理為定制功能':'展示情境資料 · 非健康或合規判定');
  }
 }
 if(id==='d'&&m.id==='idle')return revFrame(id,'exhibit-panel',`<h1>${['看見完整建築','看見樓板與核心','看見同層九戶'][seg]}</h1>${scoreFrame('exhibit')}`,'原 FBX 量體與戶別展示 · 非結構工程驗證');
 if(id==='c'&&m.id==='idle')return revFrame(id,'unique-panel',`<div class="eyebrow">ANLB · 建築承諾</div><h1>安心，有不同依據</h1><div class="unique-art">${revGraph('triad',seg)}</div><p class="unique-caption">${['安全有規格','品質有驗證','維養有紀錄'][seg]}</p>`,'概念關係圖 · 適用範圍依個案文件');
 if(m.id==='idle'&&/^s[1-4]$/.test(id)){const n=Number(id[1])-1,kind=['structure','verification','information','record-layers'][n];return revFrame(id,'unique-panel',`<div class="eyebrow">ANLB · 0${n+1}</div><h1>${['結構支撐','SGS 驗證','BIM 資訊','全透明紀錄'][n]}</h1><div class="unique-art">${revGraph(kind,seg)}</div><p class="unique-caption">${['柱、樑、樓板，各有角色','品質，有第三方把關','建造到維養，資訊接得上','看得到建築的紀錄'][n]}</p>`,'概念圖解 · 非工程計算或實際檢驗文件');}
 if(['life','bim'].includes(m.id)&&['c','d','s1','s2','s3','s4'].includes(id)){const kinds={life:{c:'radial',d:'fm-digest',s1:'material',s2:'matrix',s3:'receipt',s4:'relay'},bim:{c:'nested',d:'fm-identity',s1:'floor',s2:'topology',s3:'relations',s4:'section'}},kind=kinds[m.id][id];const plot=id==='d'?revSummary(m.id,seg):kind==='matrix'?revMatrix(seg):kind==='receipt'?revReceipt(seg):revGraph(kind,seg);return revFrame(id,`unique-panel ${id==='d'?'quiet-fm':''}`,`<div class="eyebrow">${['d','s2','s3'].includes(id)?'WELL FM':'ANLB'} · ${m.name}</div><h1>${REV_TITLES[m.id][id]}</h1><div class="unique-art">${plot}</div><p class="unique-caption">${REV_CAPTIONS[m.id][id][seg]}</p>`);}
 return null;
}
function revisionElapsed(role){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return role==='exhibit'?6:18;return frozen&&!globalThis.previewClock?(role==='exhibit'?6:14):state.elapsed;}
function refreshScores(){if(state.mode!=='data')return;const s=BOS.snapshot(state.segment,revisionElapsed(),state.scenarioSeed),map=new Map(s.records.map(r=>[r.id,r]));document.querySelectorAll('[data-score]').forEach(el=>el.textContent=map.get(el.dataset.score)?.score??'—');document.querySelectorAll('[data-value]').forEach(el=>el.textContent=formatReading(map.get(el.dataset.value)?.value??null,s.metric));document.querySelectorAll('[data-score-width]').forEach(el=>{const r=map.get(el.dataset.scoreWidth);el.style.width=(r?.score??0)+'%';el.style.background=r?.color||'#677681';});document.querySelectorAll('[data-count]').forEach(el=>el.textContent=s.histogram[+el.dataset.count]);document.querySelectorAll('[data-hist]').forEach(el=>el.style.height=(s.histogram[+el.dataset.hist]*2+8)+'px');document.querySelectorAll('[data-missing]').forEach(el=>el.textContent=s.missing);document.querySelectorAll('[data-marker]').forEach(el=>{const r=map.get(el.dataset.marker),[low,high]=s.metric.id==='air'?[0,1480]:s.metric.limits;el.style.left=Math.max(0,Math.min(100,((r?.value??low)-(s.metric.id==='air'?420:0)-low)/(high-low)*100))+'%';});document.querySelectorAll('[data-energy-deviation]').forEach(el=>{const r=map.get(el.dataset.energyDeviation),delta=s.baseline>0?(r.value/s.baseline-1)*100:0;el.style.left=(50+Math.min(0,Math.max(-50,delta/3)))+'%';el.style.width=Math.min(50,Math.abs(delta)/3)+'%';el.style.background=r.color;});document.querySelectorAll('[data-energy-delta]').forEach(el=>{const r=map.get(el.dataset.energyDelta),delta=(r.value/s.baseline-1)*100;el.textContent=(delta>=0?'+':'')+Math.round(delta)+'%';});document.querySelectorAll('[data-target-band]').forEach(el=>{if(s.metric.id==='energy')el.style.left=(s.baseline/s.metric.limits[1]*100)+'%';});document.querySelectorAll('[data-phase]').forEach(el=>el.textContent=s.phase);}
