/* Exhibition composition: native vector labels; WebGL only for spatial objects. */
const previousRevisionPanel=revisionPanel;
const METRIC_ICONS=['temperature','water','air','power'];
const BEAT_NAMES={idle:['耐震有規格','品質有驗證','房子有履歷'],life:['每一次檢驗，都有紀錄','房子的資料，一起交付','換人管理，紀錄不斷'],bim:['先找到哪一層','牆裡的管線，找得到','找到位置，也找到紀錄'],data:['溫度，逐戶看清','濕度，看見每戶差異','CO₂，觀察通風','用電，同條件比較']};
const BEAT_ICONS={idle:['shield','check','record'],life:['check','handover','tools'],bim:['layers','pipe','target'],data:METRIC_ICONS};
const GUIDES={idle:['A 看耐震主張，C 看安全依據，D 看完整建築。','檢驗勾逐一形成，讓品質主張連到驗證依據。','BIM 資訊延伸至維養，建築的紀錄持續留下。'],life:['從材料查驗位置，認識品質紀錄如何建立。','交付的不只是房子，還有查驗與設備文件。','管理者可以更替，設備與維養紀錄持續保留。'],bim:['先看全棟索引，再找到 L06 的設備區域。','從給水系統沿著管線，找到同一台 P-01。','位置、系統與檢查文件，連回同一台設備。'],data:['先看平面戶別，再看溫度資訊翻成立體建築。','從戶別色彩辨認差異，右側可讀取判讀依據。','CO₂ 用於觀察通風，不代表所有空氣品質。','同一天、同入住條件比較用電，不將低用電直接當成高能效。']};
MODES.forEach(m=>{m.segments=BEAT_NAMES[m.id];m.cues=GUIDES[m.id];STORY[m.id].forEach((s,i)=>s.title=BEAT_NAMES[m.id][i]);});
function consoleArtwork(){const m=state.mode,i=state.segment;return `<div class="current-beat" data-key="current-beat">${icon(BEAT_ICONS[m][i])}<div><span>正在展演 · ${i+1} / ${CHAPTERS[m].segmentCount}</span><strong>${BEAT_NAMES[m][i]}</strong></div></div>`;}
function artSVG(name,body){return `<svg class="ex-art" viewBox="0 0 1740 620" role="img" aria-label="${name}">${body}</svg>`;}
function tx(x,y,t,cl='',anchor='start'){return `<text class="art-label ${cl}" x="${x}" y="${y}" text-anchor="${anchor}">${t}</text>`;}
function pic(type,x,y,size=150,cl=''){return `<g class="art-icon ${cl}" transform="translate(${x} ${y})">${icon(type).replace('viewBox="0 0 120 120"',`x="0" y="0" width="${size}" height="${size}" viewBox="0 0 120 120"`)}</g>`;}
function wire(d,active=true){return `<path class="art-wire ${active?'live':''}" d="${d}"/>`;}
function reveal(min,body,extra=''){return `<g class="reveal ${state.segment>=min?'is-visible':''}" data-min="${min}" ${extra}>${body}</g>`;}
function nativeFrame(id,title,caption,body,extra='',note){const m=state.mode;return `<article class="panel revision exhibit-ui ${portrait(id)?'portrait':''} ${extra}" data-id="${id}" data-mode="${m}" data-segment="${state.segment}"><div class="kv-background" aria-hidden="true"><i></i><i></i><i></i></div>${panelHeader(id)}<h1 class="ex-title">${title}</h1><div class="ex-stage" data-key="art-${m}-${id}">${body}</div><p class="ex-caption">${caption}</p>${foot(note||(['life','bim','data'].includes(m)?'非即時資料':'概念圖解 · 適用範圍依個案文件'))}</article>`;}
function volume(kind,overlay=''){return `<div class="show-viewport" data-key="exhibit-${kind}" data-scene="${kind}"><span class="show-loading">立體圖像載入中</span></div><div class="volume-labels">${overlay}</div>`;}
function edgeLabel(y,name,detail='',side='right'){return `<div class="edge-label ${side}" style="top:${y}px"><strong>${name}</strong>${detail?`<span>${detail}</span>`:''}</div>`;}
function definitionRow(type,title,detail){return `<div class="summary-row">${icon(type)}<div><span>${title}</span><strong>${detail}</strong></div></div>`;}
function promises(seg){return artSVG('安全、品質與維養',[[170,'shield','安全','規格有依據'],[730,'check','品質','驗證有紀錄'],[1290,'tools','維養','紀錄接得上']].map(([x,ic,t,d],i)=>`<g class="promise ${seg===i?'current':''}">${pic(ic,x,45,270)}${tx(x+135,415,t,'large','middle')}${tx(x+135,510,d,'','middle')}<path class="promise-line" d="M${x-30} 575h330"/></g>`).join(''));}
function oneDocument(seg){return artSVG('單份檢驗文件：查驗、驗證、入庫',`<g transform="translate(-160 0)"><path class="document-outline" d="M300 15h870l100 100v475H300Z"/><path class="art-wire" d="M1170 15v100h100"/>${pic('check',370,55,155)}${tx(600,150,'SGS · 檢驗紀錄','large')}${['項目與文件','查驗與留存','驗證依據'].map((t,i)=>`<g class="${i<=seg?'current':'muted'}">${tx(410,295+i*115,t)}<path class="art-check" d="m1035 ${275+i*115} 32 32 70-74"/></g>`).join('')}</g>${wire('M1140 310H1220')}${pic(['target','check','record'][seg],1230,110,360)}${tx(1410,540,['項目查驗','查驗留存','依據入庫'][seg],'large','middle')}`);}
function infoLinks(seg){return artSVG('同一份 BIM 資訊連到全生命週期',`<path class="info-volume" d="M80 180l210-110 210 110v235L290 540 80 415Z M80 180l210 120 210-120M290 300v240"/>${tx(290,235,'BIM','large','middle')}${[0,1,2].map((i)=>wire(`M500 300C740 300 680 ${90+i*220} 980 ${90+i*220}`,i<=seg)+`<g class="${i===seg?'current':'muted'}">${pic(['structure','handover','tools'][i],1020,i*215,155)}${tx(1250,105+i*215,['建造','交付','維養'][i],'large')}</g>`).join('')}`);}
function recordCutaway(seg){return artSVG('建築中的資訊、品質與維養',`<path class="art-wire" d="M160 180l310-135 350 160v355H160Z"/>${[0,1,2].map((i)=>`<g style="transform:translate(${seg>=i?i*30:0}px,0px)" class="cut-layer ${i<=seg?'current':'muted'}"><path d="M190 ${210+i*100}l280-115 310 130-280 130Z"/>${wire(`M780 ${230+i*100}H1000`,i<=seg)}${pic(['layers','check','tools'][i],1040,60+i*185,125)}${tx(1220,145+i*185,['建築資訊','品質依據','維養紀錄'][i])}</g>`).join('')}`);}
function verificationWall(seg){return `<div class="verification-brand"><strong>100<span>%</span></strong><p>SGS 全品項驗證</p></div>`+artSVG('查驗、驗證與品質履歷',`<g class="verification-seal stage-${seg}"><path class="verification-solid" style="opacity:${seg?1:.16}" d="M925 40h610l50 55v405H925Z M925 40l-38 30v465h650l48-35M925 500l-38 35"/>${Array.from({length:8},(_,i)=>`<path class="verification-ray" style="opacity:${seg===1?.3:.06}" d="M${950+i*82} 65v415"/>`).join('')}${pic(['shield','check','record'][seg],1060,120,300)}${tx(1210,600,['查驗依據','驗證留存','品質履歷'][seg],'large','middle')}</g>`);}
function lifeRings(seg){return artSVG('建築生命履歷年輪',`${[265,200,130].map((r,i)=>`<circle class="life-ring ${seg>=2-i?'current':''}" cx="530" cy="310" r="${r}"/>`).join('')}${pic('record',460,240,140)}${[0,1,2].map(i=>`<g class="${i<=seg?'current':'muted'}">${wire(`M${660+i*65} ${220+i*90}H${990+i*40}V${100+i*205}H1130`,i<=seg)}${pic(['structure','handover','tools'][i],1150,25+i*200,130)}${tx(1340,110+i*200,['建造依據','交付資料','維養累積'][i])}</g>`).join('')}`);}
function archiveCabinet(seg){return `<div class="archive-art">${artSVG('WELL FM 檔案櫃',`<path class="cabinet-side" d="M180 80l110-60h580v480l-110 70H180Z"/>${[0,1,2].map(i=>`<g class="drawer ${i===seg?'current':''}" style="transform:translateX(${i===seg?75:0}px)"><rect x="180" y="${95+i*150}" width="580" height="138" rx="8"/><path d="M370 ${125+i*150}h180v18H370Z"/>${pic(['pipe','record','tools'][i],215,110+i*150,100)}${tx(375,190+i*150,['設備建檔','交付文件','維養紀錄'][i])}</g>`).join('')}`)}</div><div class="fixed-summary">${definitionRow('pipe','設備身份','P-01 · 給水設備')}${definitionRow('record',['建檔分類','交付分類','維養分類'][seg],['設備／操作資料','檢驗／設備文件','檢查／保養紀錄'][seg])}${definitionRow('clock','紀錄日期',['2026.09.06 · 建檔','2026.09.06 · 文件連結','2026.09.06 · 例行檢查'][seg])}</div>`;}
function evidenceMatrix(seg){return `<div class="proof-matrix"><div class="proof-head"><span>查驗分類</span><b>建造紀錄</b><b>交付對照</b></div>${['建材','工法','設備'].map((t,i)=>`<div class="proof-row ${seg===2&&i===0?'selected':''}"><strong>${icon(['layers','structure','pipe'][i])}${t}</strong><span>${icon('check')}<em>已留存</em></span><span class="${seg>=1?'':'unrevealed'}">${icon('handover')}<em>已關聯</em></span></div>`).join('')}</div><div class="proof-detail ${seg===2?'is-visible':''}">${icon('record')}<div><span>建材查驗 · 文件索引</span><strong>RC-01</strong><p>構件查驗摘要<br>2026.09.06</p></div></div>`;}
function repairRecord(seg){return `<div class="repair-object stage-${seg}"><div class="record-identity">${icon('tools')}<div><span>建築履歷 · 設備身份</span><strong>P-01</strong><p>給水設備 · L06</p></div></div><div class="record-unfold ${seg>=1?'is-visible':''}"><div><span>檢查項目</span><strong>接點與運轉狀態</strong></div><div><span>處理內容</span><strong>例行檢查 · 留存觀察</strong></div></div><div class="record-seal ${seg===2?'is-visible':''}">${icon('check')}<div><strong>檢查紀錄已留存</strong><span>2026.09.06 · 14:20</span></div></div></div>`;}
function handoverStage(seg){return artSVG('管理者交接與連續紀錄軌',`${tx(55,90,'管理權','small')}${tx(55,465,'建築紀錄','small')}${wire('M340 480H1590')}${[0,1,2].map((i)=>`<g class="${i===seg?'current':'muted'}">${pic('manager',370+i*510,30,190)}${tx(465+i*510,300,['建造方','管理方','維養方'][i],'large','middle')}</g>${i<2?pic('handover',665+i*510,90,125,i<seg?'':'muted'):''}${wire(`M${465+i*510} 340V480`,i<=seg)}${pic('record',400+i*510,415,130,i<=seg?'':'muted')}`).join('')}<path class="record-travel" d="M465 480H1485"/>`);}
function spaceWindow(seg){return artSVG('連續定位：全棟、L06 與 P-01',`<g class="locator-overview" style="transform:${seg?'translate(-60px,130px) scale(.3)':'translate(0px,0px) scale(1)'};opacity:${seg?.5:1}">${Array.from({length:12},(_,i)=>`<rect class="${i===6?'selected-space':''}" x="350" y="${25+i*46}" width="700" height="35"/>`).join('')}${wire('M1060 318H1280')}${tx(1310,332,'L06','large')}</g><g class="locator-detail" style="opacity:${seg?1:0};transform:${seg===2?'translate(-510px,-260px) scale(1.55)':seg===1?'translate(200px,40px) scale(.85)':'translate(540px,300px) scale(.05)'}"><path class="floor-plan" d="M160 75H1330V540H160ZM550 75v465M940 75v465M160 310h1170"/><rect class="selected-space" x="945" y="315" width="380" height="220"/><path class="route-flow" style="opacity:${seg===2?1:0}" d="M500 385H760V180H1115V400"/>${pic('target',1040,355,140)}</g>`);}
function topology(seg){const nodes=[[130,220,'water','給水系統'],[650,30,'pipe','P-01'],[650,385,'pipe','P-02'],[1230,30,'pulse','感測訊號'],[1230,385,'tools','維養關聯']];return artSVG('給水設備拓撲',`${wire('M350 320H540V130H650',true)}${wire('M540 320V480H650',seg>=1)}${wire('M850 130H1230',seg>=1)}${wire('M850 130H1070V480H1230',seg>=2)}${nodes.map(([x,y,ic,t],i)=>`<g class="topology-node ${i===0||seg>=1?'current':'muted'}">${pic(ic,x,y,190)}${tx(x+95,y+225,t,'','middle')}${i===1&&seg===2?`<circle class="locate-ring" cx="${x+95}" cy="${y+95}" r="115"/>`:''}</g>`).join('')}`);}
function fileFan(seg){return `<div class="fan-device">${icon('pipe')}<strong>P-01</strong><span>同一台設備</span></div><div class="file-fan stage-${seg}">${['操作資料','檢查文件','維養紀錄'].map((t,i)=>`<div class="fan-file ${seg>=1||i===0?'is-visible':''}" style="--i:${i}" data-key="fan-${i}">${icon(i===0?'record':i===1?'check':'tools')}<strong>${t}</strong><span>${['設備規格','例行檢查','保養計畫'][i]}</span></div>`).join('')}</div><div class="fan-link ${seg===2?'is-visible':''}">${icon('handover')}<span>文件與設備身份相連</span></div>`;}
function criterion(s){return ['目標帶 24–26°C','目標範圍 30–50% RH','室內外差值 ≤400 ppm','同條件用電中位數'][s.index];}
function bosSignals(seg){return artSVG('四類訊號匯入 WELL FM',`${[0,1,2,3].map(i=>wire(`M${200+i*440} 210C${200+i*440} 370 870 250 870 435`,i===seg)).join('')}${METRIC_ICONS.map((ic,i)=>`<g class="${i===seg?'current':'muted'}">${pic(ic,110+i*440,0,180)}${tx(200+i*440,270,BOS.metrics[i].name,'','middle')}</g>`).join('')}<rect class="bos-hub" x="530" y="410" width="680" height="195" rx="25"/>${tx(870,500,'WELL FM','hero','middle')}${tx(870,567,'訊號匯流 · 紀錄相連','','middle')}`);}
function criterionGraphic(s){const r=s.selected[1];let body='';
 if(s.index===0){const x=35+(r.value-20)/12*480;body=`<path class="criterion-line" d="M35 110H515"/><rect x="195" y="80" width="80" height="60" rx="10" class="criterion-target"/><path class="criterion-pointer" d="M${x} 55v108"/><text x="35" y="220">20°C</text><text x="515" y="220" text-anchor="end">32°C</text><text x="235" y="48" text-anchor="middle">24–26</text>`;}
 if(s.index===1){const a=r.value/100*Math.PI*2-Math.PI/2,x=275+88*Math.cos(a),y=127+88*Math.sin(a);body=`<circle class="criterion-track" cx="275" cy="127" r="88"/><circle class="criterion-range" cx="275" cy="127" r="88" pathLength="100" stroke-dasharray="20 80" stroke-dashoffset="-30" transform="rotate(-90 275 127)"/><circle cx="${x}" cy="${y}" r="12" fill="white"/><text x="275" y="143" text-anchor="middle">% RH</text><text x="45" y="220">0</text><text x="500" y="220" text-anchor="end">100</text>`;}
 if(s.index===2){const delta=Math.round(r.value-420),w=Math.min(470,delta/1200*470);body=`<text x="35" y="55">室內 − 室外</text><rect class="criterion-target" x="35" y="90" width="${w}" height="42" rx="8"/><path class="criterion-pointer" d="M192 75v75"/><text x="35" y="212">差值 ${delta} ppm</text>`;}
 if(s.index===3){const ratio=r.value/s.baseline;body=`<path class="criterion-line" d="M35 110H515"/><rect class="criterion-target" x="35" y="85" width="${Math.min(480,ratio*240)}" height="50" rx="8"/><path class="criterion-pointer" d="M275 55v110"/><text x="275" y="205" text-anchor="middle">中位數 ${s.baseline.toFixed(3)}</text>`;}
 return `<svg class="criterion-mini criterion-${s.index}" viewBox="0 0 550 245" role="img" aria-label="${criterion(s)}">${body}</svg>`;
}
function scoreExplanation(s){const r=s.selected[1],other=s.selected[0];return `<div class="score-causal"><div class="causal-reading">${icon(METRIC_ICONS[s.index])}<span>${r.id}</span><strong>${formatReading(r.value,s.metric)}</strong></div><div class="causal-arrow">→</div><div class="causal-rule"><span>判讀條件</span><strong>${criterion(s)}</strong>${criterionGraphic(s)}</div><div class="causal-arrow">→</div><div class="causal-score" style="--score-color:${r.color}"><strong>${r.score}</strong><span>目標分數 / 100</span></div></div><div class="score-record-line">${icon('record')}<span>${r.id} · 2026.09.06 · 判讀版本 1.0</span><small>另一選戶 ${other.id} · ${other.score} 分</small></div>`;}
function rawReadings(s){return `<div class="raw-symbol">${icon(METRIC_ICONS[s.index])}<strong>${s.metric.name}</strong></div><div class="raw-values">${s.selected.map(r=>`<div class="raw-row" data-house="${r.id}"><span><i style="background:${r.color}"></i>${r.id}</span><strong>${r.value===null?'—':r.value.toFixed(s.index===3?3:s.index===2?0:1)}<small>${s.metric.unit}</small></strong></div>`).join('')}</div>`;}
function distribution(s){const counts=[...s.histogram],colors=BOS.bands.map(b=>b.color);let offset=0;const circles=counts.map((n,i)=>{const c=`<circle data-band-count="${n}" data-band-offset="${offset}" cx="380" cy="310" r="245" pathLength="108" stroke="${colors[i]}" stroke-dasharray="${n} ${108-n}" stroke-dashoffset="${-offset}"/>`;offset+=n;return c;}).join(''),valid=108-s.missing,pct=Math.round((s.histogram[0]+s.histogram[1])/valid*100);return artSVG('108 戶精確比例環圖',`<g class="proportion-donut" data-key="fixed-donut" transform="rotate(-90 380 310)"><circle class="donut-base" cx="380" cy="310" r="245" stroke="${colors[0]}"/>${circles}</g>${tx(380,315,pct+'%','percentage','middle')}${tx(380,395,'全棟戶別為藍綠','','middle')}${BOS.bands.map(b=>`${b.min}–${b.max} 分`).map((t,i)=>`<rect x="860" y="${25+i*93}" width="38" height="38" rx="7" fill="${colors[i]}"/>${tx(935,60+i*93,t)}${tx(1540,60+i*93,counts[i]+' 戶','','end')}`).join('')}`)+`<div class="distribution-base">全棟 108 戶 · 藍綠 ${s.histogram[0]+s.histogram[1]} 戶</div>`;}
// The ring geometry stays fixed; only the colored arc lengths grow.
function updateDistribution(now){requestAnimationFrame(updateDistribution);const shared=globalThis.showcaseState;if(!shared||shared.mode!=='data')return;const t=shared.elapsed+(shared.playing?(now-shared.received)/1000:0),p=matchMedia('(prefers-reduced-motion: reduce)').matches?1:Math.max(0,Math.min(1,(t-1)/5));document.querySelectorAll('.proportion-donut [data-band-count]').forEach(c=>{const count=+c.dataset.bandCount,offset=+c.dataset.bandOffset,length=Math.min(count,Math.max(0,108*p-offset));c.setAttribute('stroke-dasharray',`${length} 108`);});}
requestAnimationFrame(updateDistribution);
function householdMatrix(s){return `<div class="house-matrix" data-viz="12x9-households"><div class="matrix-axis"><span>樓層</span>${Array.from({length:9},(_,u)=>`<b>U${String(u+1).padStart(2,'0')}</b>`).join('')}</div>${Array.from({length:12},(_,f)=>{const floor=12-f;return `<div class="matrix-floor"><b>R${String(floor).padStart(2,'0')}</b>${s.records.filter(r=>r.f===floor).map(r=>`<div class="house-cell ${s.selected.some(x=>x.id===r.id)?'chosen':''}" data-house="${r.id}" data-score-value="${r.score}" style="--house-color:${r.color}" aria-label="${r.id} ${r.score??'資料不足'}"><span>${s.selected.some(x=>x.id===r.id)?r.score:''}</span></div>`).join('')}</div>`;}).join('')}</div><div class="matrix-key">白框選戶：${s.selected.map(r=>`${r.id} · ${r.score} 分`).join('　／　')}</div>`;}
function recordTimeline(s){const r=s.selected[1];return `<div class="trace-house"><strong>${r.id}</strong><span>${s.metric.name} · 資料追溯</span></div><div class="trace-timeline">${[['clock','讀值時間','09.06 · 14:20'],['check','判讀版本','規則 1.0'],['tools','關聯紀錄','設備履歷索引']].map(([ic,t,v],i)=>`<section>${icon(ic)}<span>${t}</span><strong>${v}</strong></section>`).join('')}</div>`;}
function portraitNavigation(id){const m=state.mode,seg=state.segment;if(id==='s5'){const steps=m==='data'?BOS.metrics.map(x=>x.name):{idle:['耐震規格','品質驗證','建築履歷'],life:['建造留存','資料交付','維養接續'],bim:['全棟樓層','管線設備','關聯紀錄']}[m];return nativeFrame(id,m==='data'?'四項指標<br>逐戶看清':'本章三步<br>看懂建築','',`<div class="vertical-nav">${steps.map((t,i)=>`<section class="${i===seg?'current':''}">${icon(BEAT_ICONS[m][i])}<span>0${i+1}</span><strong>${t}</strong></section>`).join('')}</div>`,'nav-panel');}return null;}
revisionPanel=function(id){const m=state.mode,seg=state.segment;
 if(id==='main')return previousRevisionPanel(id).replace(/assets\/(tower|orbit|aerial)\.png/g,'assets/architecture-1600.png');
 if(id==='s5')return portraitNavigation(id);
 if(m==='idle'){
  if(id==='a')return nativeFrame(id,'核電廠同級耐震力','安全，從規格開始',`<div class="seismic-number">0.41<span>G</span></div><div class="seismic-icon">${icon(BEAT_ICONS.idle[seg])}<span>${['規格依據','品質驗證','履歷留存'][seg]}</span></div>`,'brand-spec','寶舖品牌主張 · 非地震等級或性能保證');
  if(id==='c')return nativeFrame(id,'安心，有不同依據',['安全有規格','品質有驗證','維養有紀錄'][seg],promises(seg));
  if(id==='s1')return nativeFrame(id,'結構支撐',['柱 · 垂直支撐','樑 · 水平連結','樓板 · 空間承載'][seg],volume('idle-s1',edgeLabel(65,['柱','樑','樓板'][seg],'組裝概念')),'has-volume','結構概念圖 · 非工程計算');
  if(id==='s2')return nativeFrame(id,'SGS 驗證','品質，有第三方把關',oneDocument(seg));
  if(id==='s3')return nativeFrame(id,'BIM 資訊','建造到維養，資訊接得上',infoLinks(seg));
  if(id==='s4')return nativeFrame(id,'全透明紀錄','看得到建築的紀錄',recordCutaway(seg));
 }
 if(m==='life'){
  if(id==='a')return nativeFrame(id,'SGS 全品項驗證',['每一項，都有查驗依據','品質驗證，完整留存','品質紀錄，收進履歷'][seg],verificationWall(seg),'verification-panel','SGS 100% 為品牌主張 · 驗證範圍依個案文件');
  if(id==='c')return nativeFrame(id,'建築生命履歷',['從建造，留下依據','連交付，一起留存','到維養，持續累積'][seg],lifeRings(seg));
  if(id==='d')return nativeFrame(id,'WELL FM｜履歷總覽','設備、文件、維養紀錄，在同一處',archiveCabinet(seg).replace('0 0 1740 620','0 0 1040 620'),'archive-panel');
  if(id==='s1')return nativeFrame(id,'構件查驗',['看清構件組成','剖開局部，看清查驗位置','從查驗部位，找到紀錄'][seg],volume('life-s1',seg===2?`<div class="inspection-note">${icon('record')}<span>RC-01 · 查驗摘要</span><strong>鋼筋配置／接點</strong><p>2026.09.06 · 位置已關聯</p></div>`:edgeLabel(60,seg===0?'RC 構件':'鋼筋與保護層','查驗概念')),'has-volume','構件查驗概念 · 非 FBX 實際構造');
  if(id==='s2')return nativeFrame(id,'建築品質查驗','每份文件，都有對應的位置',evidenceMatrix(seg),'matrix-panel');
  if(id==='s3')return nativeFrame(id,'設備維養履歷','一台設備，一份可追溯的紀錄',repairRecord(seg));
  if(id==='s4')return nativeFrame(id,'管理交接','換人管理，紀錄不斷',handoverStage(seg));
 }
 if(m==='bim'){
  if(id==='a')return nativeFrame(id,'BIM 全資產生命週期',['先建立建築空間','空間與系統，逐層分開','位置、系統、履歷，一起連結'][seg],volume('bim-a',`<div class="layer-labels">${['建築空間','設備系統','履歷索引'].map((t,i)=>`<div class="${i<=seg?'current':'muted'}"><b>0${i+1}</b><strong>${t}</strong><span>${['位置與量體','路徑與設備','文件與紀錄'][i]}</span></div>`).join('')}</div>`),'has-volume bim-volume');
  if(id==='c')return nativeFrame(id,'從整體，找到位置',['全棟範圍 · L06','L06 · 東側設備區','P-01 · 同一台給水設備'][seg],spaceWindow(seg));
  if(id==='d')return nativeFrame(id,'WELL FM｜設備身份','找到位置，也找到這台設備的資料',volume('bim-d',`<div class="equipment-summary">${definitionRow('pipe','P-01','給水設備 · L06')}${seg>=1?definitionRow('water','所屬系統','進水 → 加壓 → 出水'):''}${seg===2?definitionRow('record','最近紀錄','09.06 · 例行檢查'):''}</div>`),'has-volume equipment-panel');
  if(id==='s1')return nativeFrame(id,'樓層定位',['先看十二層索引','樓層堆疊，空間成立','抽出 L06，定位設備區域'][seg],volume('bim-s1',`<div class="floor-index">${Array.from({length:12},(_,i)=>`<span class="${i===6?'current':''}">L${String(12-i).padStart(2,'0')}</span>`).join('')}</div>${edgeLabel(210,'L06','東側設備區')}`),'has-volume floor-panel');
  if(id==='s2')return nativeFrame(id,'設備系統關聯','同一系統，設備關係看得見',topology(seg));
  if(id==='s3')return nativeFrame(id,'設備文件索引','文件與紀錄，連回同一台設備',fileFan(seg));
  if(id==='s4')return nativeFrame(id,'管線透視',['牆內資訊，不再被遮住','揭開牆面，看見路徑','沿著流向，找到設備'][seg],volume('bim-s4',edgeLabel(65,seg===0?'牆體剖面':'給水路徑',seg===2?'→ P-01':'管線概念')),'has-volume');
 }
 if(m==='data'){const s=BOS.snapshot(seg,revisionElapsed(),state.scenarioSeed);
  if(id==='a')return nativeFrame(id,s.metric.name+'｜看見每戶差異','平面資訊，走進整棟建築',volume('data-a',`<div class="metric-symbol">${icon(METRIC_ICONS[seg])}</div>`)+`<div class="show-palette">${BOS.bands.map(b=>`<span><i style="background:${b.color}"></i>${b.min}–${b.max}</span>`).join('')}</div>`,'has-volume bos-building');
  if(id==='c')return nativeFrame(id,'全棟訊號，匯流同一處','從不同讀值，看見每戶差異',bosSignals(seg));
  if(id==='d')return nativeFrame(id,'每個分數，都有依據','讀值與判讀條件，連回同一戶',scoreExplanation(s));
  if(id==='s1')return nativeFrame(id,'原始讀值','先看數值，再看分數',rawReadings(s));
  if(id==='s2')return nativeFrame(id,'全棟分數分布','用同一套條件，看見全棟比例',distribution(s),'distribution-panel');
  if(id==='s3')return nativeFrame(id,'每戶差異，都找得到','十二層 · 每層九戶 · 同一套色階',householdMatrix(s),'household-panel');
  if(id==='s4')return nativeFrame(id,'從分數，回查依據','讀值、判讀與關聯紀錄，接得起來',recordTimeline(s));
 }
 return previousRevisionPanel(id);
};
